FROM ubuntu:16.04

COPY ./sources.list /etc/apt/sources.list
RUN apt-get update

RUN apt-get install software-properties-common python-software-properties language-pack-en-base vim git wget curl -y
RUN locale-gen en_US.UTF-8

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8

RUN add-apt-repository ppa:ondrej/php && \
    apt-get update

RUN apt-get install php7.1-fpm php7.1-gd php7.1-cli php7.1-curl php7.1-dev php7.1-json php7.1-mbstring php7.1-mcrypt php7.1-mysql php7.1-xml php7.1-zip php-redis -y --fix-missing

# install phalcon
RUN curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash && \
    apt-get install php7.1-phalcon -y

RUN pecl install swoole && \
    echo "extension=swoole.so" > /etc/php/7.1/mods-available/swoole.ini && \
    ln -s /etc/php/7.1/mods-available/swoole.ini /etc/php/7.1/cli/conf.d/20-swoole.ini && \
    ln -s /etc/php/7.1/mods-available/swoole.ini /etc/php/7.1/fpm/conf.d/20-swoole.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer && \
    composer config -g repo.packagist composer https://packagist.phpcomposer.com

COPY ./.bashrc /root/.bashrc

# install supervisor
RUN apt-get install -y supervisor
COPY ./supervisor/ /etc/supervisor/conf.d/

# configure cron
RUN apt-get install -y cron
COPY ./cron/*.cron /cron.d/
WORKDIR /cron.d
RUN find *.cron -type f -exec cat {} \;>>/etc/crontab

COPY ./start.sh /bin/start.sh
RUN chmod +x /bin/start.sh
WORKDIR /home/wwwroot

EXPOSE 9000
ENTRYPOINT ["start.sh"]
